# Generated by Django 2.2.3 on 2019-07-23 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewableProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('short_description', models.CharField(max_length=400)),
                ('avg_review', models.FloatField()),
                ('category', models.CharField(default='body', max_length=16)),
                ('product_slug', models.CharField(default=1, max_length=200)),
                ('product_number', models.CharField(default='unorderable', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(to='main.CartProduct')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_user', models.CharField(default='anonymous', max_length=150)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 14, 31, 44, 807232), verbose_name='date published')),
                ('review_title', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('review_description', models.TextField()),
                ('purchased', models.BooleanField()),
                ('reviewableproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReviewableProduct')),
            ],
            options={
                'verbose_name_plural': 'ProductReviews',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_user', models.CharField(default='anonymous', max_length=150)),
                ('question_text', models.CharField(default='question', max_length=600)),
                ('applied_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReviewableProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_user', models.CharField(default='anonymous', max_length=150)),
                ('answer_text', models.CharField(default='answer', max_length=600)),
                ('applied_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='applied_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReviewableProduct'),
        ),
    ]
