# Generated by Django 2.2.3 on 2019-07-23 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190723_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='applied_profile',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 14, 52, 21, 584282), verbose_name='date published'),
        ),
    ]
