# Generated by Django 2.2.3 on 2019-07-23 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190723_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 15, 17, 59, 602776), verbose_name='date published'),
        ),
    ]
