# Generated by Django 2.2.3 on 2019-07-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190723_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 18, 1, 48, 719920), verbose_name='date published'),
        ),
    ]
