# Generated by Django 2.2.3 on 2019-07-24 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190723_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 18, 6, 12, 296708), verbose_name='date published'),
        ),
    ]
