# Generated by Django 2.2.3 on 2019-07-24 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190723_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 0, 22, 4, 130489), verbose_name='date published'),
        ),
    ]
