# Generated by Django 2.2.3 on 2019-07-24 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190724_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewableproduct',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 14, 20, 57, 103924), verbose_name='date published'),
        ),
    ]
