# Generated by Django 2.2.3 on 2019-07-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190724_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 16, 14, 44, 23723), verbose_name='date published'),
        ),
    ]
