# Generated by Django 2.2.3 on 2019-07-25 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190724_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 17, 10, 39, 825277), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.FloatField()),
                ('orders', models.ManyToManyField(blank=True, to='main.CartProduct')),
            ],
        ),
    ]
