# Generated by Django 2.2.3 on 2019-07-25 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190724_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 17, 11, 35, 694424), verbose_name='date published'),
        ),
    ]
