# Generated by Django 2.2.3 on 2019-09-03 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190902_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 18, 41, 5, 922736), verbose_name='date published'),
        ),
    ]
