# Generated by Django 2.2.3 on 2019-09-03 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190902_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 39, 1, 596365), verbose_name='date published'),
        ),
    ]
