# Generated by Django 2.2.3 on 2019-09-03 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190902_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 41, 34, 402929), verbose_name='date published'),
        ),
    ]
