# Generated by Django 2.2.3 on 2019-09-03 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190902_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpageimages',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 20, 54, 8, 22340), verbose_name='date published'),
        ),
    ]
