# Generated by Django 2.2.3 on 2019-09-04 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190903_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 21, 14, 35, 924246), verbose_name='date published'),
        ),
    ]
