# Generated by Django 2.2.3 on 2019-09-10 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190903_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 20, 45, 4, 317043), verbose_name='date published'),
        ),
    ]
